openapi: 3.0.3
info:
  title: Companies API
  version: "1.0.0"
  description: API for managing buildings and apartments

servers:
  - url: http://localhost:8012

paths:
  /companies/{uuid}:
    get:
      summary: Get company by id
      tags:
        - Companies
      responses:
        '200':
          description:  Got
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
    delete:
      summary: Delete company by id
      tags:
        - Companies
      responses:
        '200':
          description: Successfully deleted
  /companies/:
    put:
      summary: Update Company
      tags:
        - Companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '200':
          description: Updated
    post:
      summary: Create Company
      tags:
        - Companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
  /auth/register:
    post:
      summary: Register User
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialsRequest'
      responses:
        '200':
          description: Successfully registered
  /auth/login:
    put:
      summary: Login User
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialsRequest'
      responses:
        '200':
          description: Successfully login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialsResponse'
components:
  schemas:
    Company:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          example: "LLC XM"
        description:
          type: string
          example: "Binance.com core partner"
        employees_count:
          type: integer
          format: int32
          example: 14003
        is_registered:
          type: boolean
          example: true
        type:
          $ref: '#/components/schemas/CompanyType'
      required:
        - uuid
        - name
        - employees_count
        - is_registered
        - type
    CompanyType:
      type: string
      enum:
        - corporation
        - non_profit
        - cooperative
        - sole_proprietorship
      example: corporation
    CredentialsRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    CredentialsResponse:
      type: object
      required:
        - access_token
      properties:
        access_token:
          type: string